# Generated by Django 4.0.5 on 2022-08-02 09:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitals',
            name='location',
        ),
        migrations.AddField(
            model_name='hospitals',
            name='address',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospitals',
            name='latitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospitals',
            name='longitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
