# Generated by Django 4.0.5 on 2022-08-05 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0003_hospitals_photo_hospitals_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitals',
            name='video',
        ),
    ]
