# Generated by Django 4.0.5 on 2022-08-05 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0005_hospitals_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitals',
            name='photo',
            field=models.FileField(upload_to='videos/'),
        ),
    ]
