# Generated by Django 4.0.5 on 2022-08-05 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0007_alter_hospitals_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitals',
            name='video',
        ),
    ]
