# Generated by Django 4.0.5 on 2022-08-05 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0008_remove_hospitals_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitals',
            name='photo',
        ),
    ]
