# Generated by Django 4.0.5 on 2022-08-05 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0009_remove_hospitals_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitals',
            name='photo',
            field=models.FileField(default=1, upload_to='photos/'),
            preserve_default=False,
        ),
    ]
