# Generated by Django 4.0.5 on 2022-08-05 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0010_hospitals_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitals',
            name='video',
            field=models.FileField(default=1, upload_to='videos/'),
            preserve_default=False,
        ),
    ]
