# Generated by Django 3.2 on 2022-08-18 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0012_auto_20220818_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitals',
            name='latitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospitals',
            name='longitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
