# Generated by Django 4.0.5 on 2022-08-22 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0013_auto_20220818_0800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitals',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='hospitals',
            name='longitude',
        ),
    ]
