# Generated by Django 4.0.5 on 2022-08-23 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0014_remove_hospitals_latitude_remove_hospitals_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitals',
            name='latitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospitals',
            name='longitude',
            field=models.FloatField(default=0.00017202081451855674),
            preserve_default=False,
        ),
    ]
