# Generated by Django 3.2 on 2022-07-28 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=20)),
                ('specialist', models.CharField(choices=[('allergy and immunology', 'Allergy & Immunology'), ('anesthesiology', 'Anesthesiology'), ('dermatology', 'Dermatology'), ('diagnostic radiology', 'diagnostic radiology')], max_length=100)),
            ],
        ),
    ]
