# Generated by Django 3.2 on 2022-08-05 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctors_hospitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_id', models.IntegerField()),
                ('doctor_id', models.IntegerField()),
                ('day', models.CharField(choices=[('sunday', 'Sunday'), ('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday')], max_length=20)),
                ('startTime', models.TimeField(verbose_name='%H:%M')),
                ('endTime', models.TimeField(verbose_name='%H:%M')),
            ],
        ),
        migrations.AlterField(
            model_name='doctors',
            name='specialist',
            field=models.CharField(choices=[('allergy and immunology', 'Allergy & Immunology'), ('anesthesiology', 'Anesthesiology'), ('dermatology', 'Dermatology'), ('diagnostic radiology', 'Diagnostic radiology')], max_length=100),
        ),
    ]
