# Generated by Django 4.0.5 on 2022-07-29 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctors_hospitals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='specialist',
            field=models.CharField(choices=[('allergy and immunology', 'Allergy & Immunology'), ('anesthesiology', 'Anesthesiology'), ('dermatology', 'Dermatology'), ('diagnostic radiology', 'Diagnostic radiology')], max_length=100),
        ),
    ]
