# Generated by Django 3.2 on 2022-08-09 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_auto_20220805_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='specialist',
            field=models.CharField(choices=[('Allergy And Immunology', 'Allergy & Immunology'), ('Anesthesiology', 'Anesthesiology'), ('Dermatology', 'Dermatology'), ('Diagnostic Radiology', 'Diagnostic Radiology')], max_length=100),
        ),
    ]
