# Generated by Django 3.2 on 2022-08-15 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20220815_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='fee',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
